## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

# Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

# Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your data checkpoint feedback

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [2]:
# # Setup code -- Run only once after cloning!!! 
# #
# # this code downloads the data from its source to the `data/00-raw/` directory
# # if the data hasn't updated you don't need to do this again!

# # if you don't already have these packages (you should!) uncomment this line
# # %pip install requests tqdm

# import sys
# sys.path.append('./modules') # this tells python where to look for modules to import

# import get_data # this is where we get the function we need to download data

# # replace the urls and filenames in this list with your actual datafiles
# # yes you can use Google drive share links or whatever
# # format is a list of dictionaries; 
# # each dict has keys of 
# #   'url' where the resource is located
# #   'filename' for the local filename where it will be stored 
# datafiles = [
#     { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
#     { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
# ]

# get_data.get_raw(datafiles,destination_directory='data/00-raw/')

### Dataset #1 

Instructions: REPLACE the contents of this cell and the one below with your work, including any updates to recover points lost in your data checkpoint feedback

In [3]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### Dataset #2
 as above, add any more copies of this that you need to given how many datasets you have

In [4]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

In [5]:
!pip install catboost -q

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re 

from catboost import Pool, CatBoostRegressor

from scipy.sparse import hstack
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [7]:
df = pd.read_csv('data/02-processed/isekai_final.csv')

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [8]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [9]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

In [10]:
df

,mal_id,title,type,status,score,start_date,rank,popularity,members,favorites,genres,themes,episodes,season,year,season_length
0,58985,0-saiji Start Dash Monogatari,TV,Finished Airing,5.43,2024-07-07 00:00:00+00:00,12703.0,6424,12263,24,"['Adventure', 'Fantasy']","['Isekai', 'Reincarnation']",12.0,Summer,2024,Short
1,60425,0-saiji Start Dash Monogatari Season 2,TV,Finished Airing,5.63,2025-01-05 00:00:00+00:00,12053.0,9660,4376,10,"['Adventure', 'Fantasy']","['Isekai', 'Reincarnation']",12.0,Winter,2025,Short
2,41380,100-man no Inochi no Ue ni Ore wa Tatteiru,TV,Finished Airing,6.52,2020-10-02 00:00:00+00:00,7107.0,826,324016,701,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Isekai'],12.0,Fall,2020,Short
3,44881,100-man no Inochi no Ue ni Ore wa Tatteiru 2nd...,TV,Finished Airing,6.79,2021-07-10 00:00:00+00:00,5509.0,1453,182088,640,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Isekai'],12.0,Summer,2021,Short
4,306,Abenobashi Mahou☆Shoutengai,TV,Finished Airing,7.21,2002-04-04 00:00:00+00:00,3376.0,2364,96358,380,"['Award Winning', 'Comedy', 'Fantasy', 'Ecchi']","['Isekai', 'Parody']",13.0,Spring,2002,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,58502,Zenshuu.,TV,Finished Airing,7.58,2025-01-05 00:00:00+00:00,1705.0,1706,149997,865,"['Action', 'Fantasy']",['Isekai'],12.0,Winter,2025,Short
241,1195,Zero no Tsukaima,TV,Finished Airing,7.20,2006-07-03 00:00:00+00:00,3495.0,243,855507,8120,"['Action', 'Adventure', 'Comedy', 'Fantasy', '...","['Harem', 'Isekai', 'School']",13.0,Summer,2006,Short
242,11319,Zero no Tsukaima F,TV,Finished Airing,7.41,2012-01-07 00:00:00+00:00,2423.0,576,439736,1228,"['Action', 'Adventure', 'Comedy', 'Fantasy', '...","['Harem', 'Isekai', 'School']",12.0,Winter,2012,Short
243,1840,Zero no Tsukaima: Futatsuki no Kishi,TV,Finished Airing,7.39,2007-07-09 00:00:00+00:00,2490.0,465,522752,1290,"['Action', 'Adventure', 'Comedy', 'Fantasy', '...","['Harem', 'Isekai', 'School']",12.0,Summer,2007,Short
244,3712,Zero no Tsukaima: Princesses no Rondo,TV,Finished Airing,7.31,2008-07-07 00:00:00+00:00,2856.0,543,462835,809,"['Action', 'Adventure', 'Comedy', 'Fantasy', '...","['Harem', 'Isekai', 'School']",12.0,Summer,2008,Short

#### train a catboost regressor for rating prediction based on tf-idf synopsis embeddings + other features for funsies

In [11]:
# pull + clean synopsis 
df_clean = pd.read_csv('data/02-processed/isekai_clean.csv')
df = df.merge(df_clean[df_clean['type'] == 'TV'][['mal_id', 'synopsis']], how  = 'left', on = 'mal_id')

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    return text

df['synopsis'] = df['synopsis'].apply(lambda x: clean_text(x))

# get embeddings
tfidf = TfidfVectorizer(stop_words='english', max_features=3000, min_df=2)
tfidf_matrix = tfidf.fit_transform(df['synopsis'])
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=[f"tfidf_{c}" for c in tfidf.get_feature_names_out()], index=df.index) # add renaming so it doesn't conflict with our existing col names
tfidf_df

,tfidf_10,tfidf_12,tfidf_15,tfidf_16,tfidf_17,tfidf_20,tfidf_25,tfidf_30,tfidf_300,tfidf_34,...,tfidf_youthful,tfidf_yui,tfidf_yukinari,tfidf_yumina,tfidf_yuna,tfidf_yuu,tfidf_yuuki,tfidf_yuusuke,tfidf_zapped,tfidf_zero
0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
1,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
2,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.126562,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.133675,0.0,0.000000
3,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.119433,0.0,0.000000
4,0.0,0.15298,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
241,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.159676
242,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.250245
243,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.109241
244,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000

In [12]:
# process those two cols with list of entries
def parse_list_column(s):
    s = s.strip("[]")
    items = s.split(",")
    items = [item.strip().strip("'\"") for item in items if item.strip().strip("'\"")]
    return items

df['genres_list'] = df['genres'].apply(parse_list_column)
df['themes_list'] = df['themes'].apply(parse_list_column)

mlb_genres = MultiLabelBinarizer()
genres_encoded = mlb_genres.fit_transform(df['genres_list'])
mlb_themes = MultiLabelBinarizer()
themes_encoded = mlb_themes.fit_transform(df['themes_list'])

genres_df = pd.DataFrame(genres_encoded, columns=[f"genre_{c}" for c in mlb_genres.classes_], index=df.index)
themes_df = pd.DataFrame(themes_encoded, columns=[f"theme_{c}" for c in mlb_themes.classes_], index=df.index)

# prepare input and target
cat_cols = ['type', 'status', 'season', 'season_length']
num_cols = ['rank', 'popularity', 'members', 'favorites', 'episodes', 'year'] 
target_col = 'score'

cat_df = df[cat_cols + num_cols]
X_final = pd.concat([cat_df, tfidf_df, genres_df, themes_df], axis=1)
y_final = df[target_col]

X_train, X_temp, y_train, y_temp = train_test_split(X_final, y_final, test_size=0.2, random_state = 42)
X_eval, X_test, y_eval, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state = 42)

In [13]:
train_pool = Pool(data = X_train, label = y_train, cat_features = cat_cols)
eval_pool = Pool(data = X_eval, label = y_eval, cat_features = cat_cols)
test_pool = Pool(data = X_test, label = y_test, cat_features = cat_cols)

In [14]:
model = CatBoostRegressor(iterations = 500, learning_rate = 0.05, depth = 7, verbose = 50)
model.fit(train_pool, eval_set = eval_pool)

0:	learn: 0.6531694	test: 0.7734269	best: 0.7734269 (0)	total: 83.6ms	remaining: 41.7s
50:	learn: 0.1573242	test: 0.3275291	best: 0.3275291 (50)	total: 921ms	remaining: 8.1s
100:	learn: 0.0606828	test: 0.2397419	best: 0.2397419 (100)	total: 1.67s	remaining: 6.61s
150:	learn: 0.0351158	test: 0.2163989	best: 0.2163973 (149)	total: 2.4s	remaining: 5.54s
200:	learn: 0.0237192	test: 0.2077736	best: 0.2077736 (200)	total: 3.12s	remaining: 4.64s
250:	learn: 0.0170353	test: 0.2054737	best: 0.2054737 (250)	total: 3.84s	remaining: 3.81s
300:	learn: 0.0132189	test: 0.2047259	best: 0.2046297 (299)	total: 4.57s	remaining: 3.02s
350:	learn: 0.0105459	test: 0.2040676	best: 0.2040262 (349)	total: 5.29s	remaining: 2.25s
400:	learn: 0.0085720	test: 0.2035252	best: 0.2035252 (400)	total: 6.05s	remaining: 1.49s
450:	learn: 0.0071245	test: 0.2033715	best: 0.2033323 (430)	total: 6.82s	remaining: 741ms
499:	learn: 0.0058835	test: 0.2030412	best: 0.2030412 (499)	total: 7.53s	remaining: 0us

bestTest = 0.2030411541
bestIteration = 499

CatBoostRegressor(depth=7, iterations=500, learning_rate=0.05, loss_function='RMSE', verbose=50)

In [15]:
# some metrics
y_pred = model.predict(test_pool)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"metrics on test set --> rmse: {rmse:.2f}, mae: {mae:.2f}, r2: {r2:.2f}")

metrics on test set --> rmse: 0.30, mae: 0.10, r2: 0.71

In [16]:
# find most decisive feature
importance = model.get_feature_importance(train_pool)
features = X_train.columns
feat_df = pd.DataFrame({'feature': features, 'importance': importance}).sort_values(by = 'importance', ascending = False)

In [17]:
feat_df[:10]

            feature  importance
4              rank   87.516433
7         favorites    2.856827
5        popularity    2.510880
6           members    0.801735
2252    tfidf_world    0.389586
1758     tfidf_save    0.249950
2269    tfidf_years    0.224764
1248      tfidf_mal    0.194715
634   tfidf_efforts    0.168220
505   tfidf_decides    0.166799

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them